/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Deletes ALL existing entries
  await knex("companies").del();
  await knex("companies").insert([
    {
      id: 1,
      company_name: "ABC Industries",
      address: "503 Broadway",
      city: "New York",
      country: "USA",
      contact_name: "Parmin Aujla",
      contact_position: "Warehouse Manager",
      contact_phone: "+1 (646) 123-1234",
      contact_email: "paujla@instock.com",
    },
    {
      id: 2,
      company_name: "XYZ Corporation",
      address: "123 Main Street",
      city: "Los Angeles",
      country: "USA",
      contact_name: "John Smith",
      contact_position: "CEO",
      contact_phone: "+1 (310) 555-5678",
      contact_email: "jsmith@xyzcorp.com",
    },
    {
      id: 3,
      company_name: "Global Innovations Ltd.",
      address: "45 Innovation Avenue",
      city: "London",
      country: "UK",
      contact_name: "Emily Johnson",
      contact_position: "Marketing Director",
      contact_phone: "+44 20 1234 5678",
      contact_email: "ejohnson@globalinnov.com",
    },
    {
      id: 4,
      company_name: "Sunset Technologies",
      address: "789 Tech Road",
      city: "San Francisco",
      country: "USA",
      contact_name: "Alex Chen",
      contact_position: "CTO",
      contact_phone: "+1 (415) 987-6543",
      contact_email: "achen@sunsettech.com",
    },
    {
      id: 5,
      company_name: "Innovate Solutions",
      address: "456 Innovation Street",
      city: "Berlin",
      country: "Germany",
      contact_name: "Sophie Müller",
      contact_position: "Product Manager",
      contact_phone: "+49 30 9876 5432",
      contact_email: "smuller@innovatesol.com",
    },
    {
      id: 6,
      company_name: "Pacific Ventures",
      address: "567 Ocean Drive",
      city: "Sydney",
      country: "Australia",
      contact_name: "Liam Johnson",
      contact_position: "Finance Director",
      contact_phone: "+61 2 8765 4321",
      contact_email: "ljohnson@pacificventures.com",
    },
    {
      id: 7,
      company_name: "Mountain Innovations",
      address: "Mountain View",
      city: "Denver",
      country: "USA",
      contact_name: "Ava Rodriguez",
      contact_position: "HR Manager",
      contact_phone: "+1 (303) 555-7890",
      contact_email: "arodriguez@mountaininnov.com",
    },
    {
      id: 8,
      company_name: "EcoTech Solutions",
      address: "Green Street",
      city: "Vancouver",
      country: "Canada",
      contact_name: "Oliver Green",
      contact_position: "Environmental Officer",
      contact_phone: "+1 (604) 789-1234",
      contact_email: "ogreen@ecotechsol.com",
    },
    {
      id: 9,
      company_name: "Dynamic Designs",
      address: "123 Design Avenue",
      city: "Tokyo",
      country: "Japan",
      contact_name: "Yuki Tanaka",
      contact_position: "Lead Designer",
      contact_phone: "+81 3 4567 8901",
      contact_email: "ytanaka@dynamicdesigns.com",
    },
    {
      id: 10,
      company_name: "Future Innovations",
      address: "789 Tomorrow Street",
      city: "Paris",
      country: "France",
      contact_name: "Juliette Martin",
      contact_position: "Innovation Officer",
      contact_phone: "+33 1 2345 6789",
      contact_email: "jmartin@futureinnov.com",
    },
    {
      id: 11,
      company_name: "Data Dynamics",
      address: "Data Drive",
      city: "Seattle",
      country: "USA",
      contact_name: "Daniel Wang",
      contact_position: "Data Scientist",
      contact_phone: "+1 (206) 987-6543",
      contact_email: "dwang@datadynamics.com",
    },
    {
      id: 12,
      company_name: "Quantum Innovations",
      address: "Quantum Street",
      city: "Mumbai",
      country: "India",
      contact_name: "Priya Patel",
      contact_position: "Quantum Physicist",
      contact_phone: "+91 22 8765 4321",
      contact_email: "ppatel@quantuminnov.com",
    },
    {
      id: 13,
      company_name: "Solar Solutions",
      address: "456 Solar Avenue",
      city: "Rio de Janeiro",
      country: "Brazil",
      contact_name: "Rafael Silva",
      contact_position: "Solar Energy Specialist",
      contact_phone: "+55 21 9876 5432",
      contact_email: "rsilva@solarsol.com",
    },
    {
      id: 14,
      company_name: "Tech Trends",
      address: "789 Tech Boulevard",
      city: "Austin",
      country: "USA",
      contact_name: "Emma Davis",
      contact_position: "Tech Analyst",
      contact_phone: "+1 (512) 555-7890",
      contact_email: "edavis@techtrends.com",
    },
    {
      id: 15,
      company_name: "Oceanic Ventures",
      address: "Ocean Drive",
      city: "Cape Town",
      country: "South Africa",
      contact_name: "Liam Ngubane",
      contact_position: "Marine Biologist",
      contact_phone: "+27 21 3456 7890",
      contact_email: "lngubane@oceanicventures.com",
    },
    {
      id: 16,
      company_name: "Green Energy Solutions",
      address: "Green Energy Street",
      city: "Stockholm",
      country: "Sweden",
      contact_name: "Eva Larsson",
      contact_position: "Sustainability Manager",
      contact_phone: "+46 8 1234 5678",
      contact_email: "elarsson@greenenergy.com",
    },
    {
      id: 17,
      company_name: "Innovative Systems",
      address: "123 Innovation Road",
      city: "Seoul",
      country: "South Korea",
      contact_name: "Joon Kim",
      contact_position: "System Architect",
      contact_phone: "+82 2 9876 5432",
      contact_email: "jkim@innovsys.com",
    },
    {
      id: 18,
      company_name: "Skyline Technologies",
      address: "789 Skyline Street",
      city: "Dubai",
      country: "UAE",
      contact_name: "Fatima Al-Mansoori",
      contact_position: "IT Director",
      contact_phone: "+971 4 123 4567",
      contact_email: "falmansoori@skylinetech.com",
    },
    {
      id: 19,
      company_name: "Mega Motors",
      address: "123 Auto Avenue",
      city: "Toronto",
      country: "Canada",
      contact_name: "Michael Johnson",
      contact_position: "CEO",
      contact_phone: "+1 (416) 555-6789",
      contact_email: "mjohnson@megamotors.com",
    },
    {
      id: 20,
      company_name: "Digital Dynamics",
      address: "456 Digital Drive",
      city: "Shanghai",
      country: "China",
      contact_name: "Li Wei",
      contact_position: "Digital Marketing Manager",
      contact_phone: "+86 21 8765 4321",
      contact_email: "lwei@digitaldyn.com",
    },
    {
      id: 21,
      company_name: "Dynamic Innovations",
      address: "789 Innovation Lane",
      city: "Moscow",
      country: "Russia",
      contact_name: "Sergei Ivanov",
      contact_position: "Innovation Officer",
      contact_phone: "+7 495 123 4567",
      contact_email: "sivanov@dynamicinnov.com",
    },
    {
      id: 22,
      company_name: "Aqua Solutions",
      address: "Aqua Avenue",
      city: "Sydney",
      country: "Australia",
      contact_name: "Isabella White",
      contact_position: "Water Treatment Specialist",
      contact_phone: "+61 2 8765 4321",
      contact_email: "iwhite@aquasol.com",
    },
    {
      id: 23,
      company_name: "Swift Technologies",
      address: "Swift Street",
      city: "New York",
      country: "USA",
      contact_name: "Andrew Taylor",
      contact_position: "Software Engineer",
      contact_phone: "+1 (646) 555-7890",
      contact_email: "ataylor@swifttech.com",
    },
    {
      id: 24,
      company_name: "Solar Innovations",
      address: "123 Solar Street",
      city: "São Paulo",
      country: "Brazil",
      contact_name: "Camila Oliveira",
      contact_position: "Solar Engineer",
      contact_phone: "+55 11 9876 5432",
      contact_email: "coliveira@solarinnov.com",
    },
    {
      id: 25,
      company_name: "Quantum Systems",
      address: "Quantum Street",
      city: "Berlin",
      country: "Germany",
      contact_name: "Maximilian Müller",
      contact_position: "Quantum Computing Scientist",
      contact_phone: "+49 30 1234 5678",
      contact_email: "mmuller@quantumsys.com",
    },
    {
      id: 26,
      company_name: "Tech Innovations",
      address: "Tech Avenue",
      city: "Tokyo",
      country: "Japan",
      contact_name: "Yuki Tanaka",
      contact_position: "Tech Lead",
      contact_phone: "+81 3 4567 8901",
      contact_email: "ytanaka@techinnov.com",
    },
    {
      id: 27,
      company_name: "InnoTech Solutions",
      address: "InnoTech Street",
      city: "Paris",
      country: "France",
      contact_name: "Sophie Lefevre",
      contact_position: "Innovation Specialist",
      contact_phone: "+33 1 2345 6789",
      contact_email: "slefevre@innotechsol.com",
    },
    {
      id: 28,
      company_name: "Dynamic Designs",
      address: "789 Design Lane",
      city: "Vancouver",
      country: "Canada",
      contact_name: "Ethan Johnson",
      contact_position: "Lead Designer",
      contact_phone: "+1 (604) 789-1234",
      contact_email: "ejohnson@dynamicdesigns.com",
    },
    {
      id: 29,
      company_name: "Future Solutions",
      address: "123 Future Street",
      city: "Seoul",
      country: "South Korea",
      contact_name: "Min-Ho Kim",
      contact_position: "Future Analyst",
      contact_phone: "+82 2 9876 5432",
      contact_email: "mhkim@futuresol.com",
    },
    {
      id: 30,
      company_name: "Global Ventures",
      address: "789 Global Drive",
      city: "Dubai",
      country: "UAE",
      contact_name: "Fatima Al-Mansoori",
      contact_position: "Business Development Manager",
      contact_phone: "+971 4 123 4567",
      contact_email: "falmansoori@globalventures.com",
    },
  ]);
};
